trainingdata: "data/raw/training_set"
testingdata: "data/raw/test_set/"
dataprocesseddirectory: "data/processed/"
modelpath: "models/"

model: "KNN"

resultsrawpath: "results/results_raw_"
resultsevaluatedpath: "results/results_evaluate_"

figuredirectory: "reports/figures/"
