trainingdata: "data/raw/training_set"
testingdata: "data/raw/test_set/"
dataprocesseddirectory: "data/processed/"
modelpath: "models/"
model: "MLP"

resultsrawpath: "results/results_raw_{{model}}.p"
resultsevaluatedpath: "results/results_evaluate_{{model}}.p"

figuredirectory: "reports/figures/"
